# Generated by Django 3.2.4 on 2023-06-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20230529_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.CharField(default='B', max_length=10),
        ),
    ]
